name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type: feature", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        We love hearing ideas from our community. Please fill out this form to help us understand your suggestion.

  - type: textarea
    id: problem
    attributes:
      label: 💡 Idea/Problem Statement
      description: What problem does this feature solve? What's currently difficult or impossible to do?
      placeholder: |
        Describe your idea. What should it look like? How should it work?
        Include specific details about the user interface, functionality, etc.
        Example: "As a student, I find it difficult to track my progress across multiple courses because..."
        or "Currently there's no way to..."
        or "I want to be able to..."
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 👤 Who would benefit?
      description: Which type of users would benefit most from this feature?
      multiple: true
      options:
        - Students
        - Alumni
        - Mentors
        - Instructors
        - Administrators
        - All users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 📈 Priority Level
      description: How important is this feature to you?
      options:
        - "🔥 High - This would significantly improve my experience"
        - "📊 Medium - This would be a nice improvement"
        - "📝 Low - This would be a small enhancement"
    validations:
      required: true

  - type: textarea
    id: technical-considerations
    attributes:
      label: ⚙️ Other Considerations
      description: |
        Use Cases, Technical Considerations, etc.
        Don't worry if you're not technical - this is completely optional!
      placeholder: |
        User stories for students, mentors, instructors, etc.
        If you have technical background, feel free to share:
        - Potential implementation approaches
        - Related technologies or libraries

  - type: dropdown
    id: complexity
    attributes:
      label: 🧩 Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "🟢 Simple - Small UI change or minor functionality"
        - "🟡 Medium - New component or moderate feature"
        - "🔴 Complex - Major feature requiring significant development"
        - "❓ I'm not sure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution Interest
      description: Would you be interested in helping implement this feature?
      options:
        - label: "Yes, I'd like to work on this feature myself"
        - label: "Yes, I'd like to help but would need guidance"
        - label: "Maybe, depending on the complexity"
        - label: "No, I'm just suggesting the idea"

  - type: checkboxes
    id: terms
    attributes:
      label: 📋 Checklist
      description: Please confirm the following
      options:
        - label: This feature aligns with CODAC's mission as a learning platform
          required: true

  - type: markdown
    attributes:
      value: |
        ### 🌟 Thank you for your suggestion!

        Feature requests help shape the future of CODAC and make it better for everyone.

        **What happens next?**
        1. The community and maintainers will review your request
        2. We'll discuss feasibility and priority
        3. The request will be labeled and potentially added to our roadmap
        4. Community members may volunteer to implement it

        **Want to implement this yourself?**
        - Check out our [Contributing Guide](../../CONTRIBUTING.md)
        - Join our community discussions to get help and feedback
        - Start with smaller issues to get familiar with the codebase

        **Help us prioritize:**
        - 👍 Give this issue a thumbs up if you want this feature
        - 💬 Comment with additional use cases or requirements
        - 🔄 Share with other community members who might benefit
