name: ❓ Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        We're here to help! 🤗 Don't hesitate to ask questions - everyone was a beginner once.

        **Before you start:** Please search existing issues and discussions to see if your question was already answered.

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Ask your question clearly and provide context
      placeholder: I'm trying to understand how to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: What category does your question fall into?
      options:
        - Getting started / Setup
        - Understanding the code
        - Contributing process
        - Feature usage
        - Technical issue
        - Other
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What have you tried so far?
      description: Let us know what you've already attempted
      placeholder: I tried...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any additional information that might help us answer your question
      placeholder: Any error messages, screenshots, or other relevant details?

  - type: checkboxes
    id: experience
    attributes:
      label: Your experience level
      description: This helps us tailor our response (optional)
      options:
        - label: I'm new to programming
        - label: I'm new to open source
        - label: I'm new to this tech stack
        - label: I'm experienced but new to this project

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for my question
          required: true
        - label: I have provided enough context for others to understand my question
          required: true
